# Generated by Django 4.1.3 on 2023-01-31 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.TextField()),
                ('FRID', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='AnimationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=200)),
                ('FRID', models.CharField(max_length=6)),
                ('Description', models.TextField()),
            ],
        ),
    ]
