# Generated by Django 4.1.3 on 2023-02-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimationStudio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animationdata',
            name='Title',
            field=models.CharField(default='wgpowers98', max_length=40),
            preserve_default=False,
        ),
    ]
