# Generated by Django 4.1.3 on 2023-02-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimationStudio', '0002_animationdata_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=40)),
                ('FRID', models.CharField(max_length=6)),
            ],
        ),
        migrations.DeleteModel(
            name='AnimationInfo',
        ),
        migrations.AddField(
            model_name='animationdata',
            name='Description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
