# Generated by Django 4.1.1 on 2023-02-11 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnimationStudio', '0002_animationdata_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnimationInfo',
        ),
    ]
