# Generated by Django 4.1.3 on 2023-02-12 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnimationStudio', '0003_delete_animationinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animationdata',
            old_name='FRID',
            new_name='UID',
        ),
    ]
