# Generated by Django 4.1.3 on 2023-02-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimationStudio', '0004_rename_frid_animationdata_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='animationdata',
            name='Description',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
    ]
