# Generated by Django 4.1.3 on 2023-02-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimationStudio', '0005_animationdata_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animationdata',
            name='Description',
            field=models.TextField(null=True),
        ),
    ]
